#pragma once

#include "layer_alternatives.h"

#if !defined(QUINOA_LAYER_DEF)
  #if defined (QUINOA_LAYERS_FLIP)
      #define QUINOA_LAYER_BASE QUINOA_ALTERNATIVES_BASE_COLEMAKDH_FLIP
    #endif
  #else
    #if defined (QUINOA_ALPHAS_AZERTY)
      #define QUINOA_LAYER_BASE QUINOA_ALTERNATIVES_BASE_AZERTY
    #endif
  #endif
#if !defined(QUINOA_LAYERMAPPING_BASE)
  #define QUINOA_LAYERMAPPING_BASE QUINOA_MAPPING
#endif

#if !defined(QUINOA_LAYER_EXTRA)
  #if defined (QUINOA_LAYERS_FLIP)
  #else
    #if defined (QUINOA_EXTRA_AZERTY)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_AZERTY
    #elif defined (QUINOA_EXTRA_BEAKL15)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_BEAKL15
    #elif defined (QUINOA_EXTRA_COLEMAK)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_COLEMAK
    #elif defined (QUINOA_EXTRA_COLEMAKDH)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_COLEMAKDH
    #elif defined (QUINOA_EXTRA_COLEMAKDHK)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_COLEMAKDHK
    #elif defined (QUINOA_EXTRA_DVORAK)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_DVORAK
    #elif defined (QUINOA_EXTRA_HALMAK)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_HALMAK
    #elif defined (QUINOA_EXTRA_WORKMAN)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_WORKMAN
    #elif defined (QUINOA_EXTRA_QWERTY)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_QWERTY
    #elif defined (QUINOA_EXTRA_QWERTZ)
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_QWERTZ
    #else
      #define QUINOA_LAYER_EXTRA QUINOA_ALTERNATIVES_BASE_QWERTY
    #endif
  #endif
#endif
#if !defined(QUINOA_LAYERMAPPING_EXTRA)
  #define QUINOA_LAYERMAPPING_EXTRA QUINOA_MAPPING
#endif

#if !defined(QUINOA_LAYER_TAP)
  #if defined (QUINOA_LAYERS_FLIP)
    #if defined (QUINOA_TAP_AZERTY)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_AZERTY_FLIP
    #elif defined (QUINOA_TAP_BEAKL15)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_BEAKL15_FLIP
    #elif defined (QUINOA_TAP_COLEMAK)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_COLEMAK_FLIP
    #elif defined (QUINOA_TAP_COLEMAKDH)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_COLEMAKDH_FLIP
    #elif defined (QUINOA_TAP_COLEMAKDHK)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_COLEMAKDHK_FLIP
    #elif defined (QUINOA_TAP_DVORAK)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_DVORAK_FLIP
    #elif defined (QUINOA_TAP_HALMAK)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_HALMAK_FLIP
    #elif defined (QUINOA_TAP_WORKMAN)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_WORKMAN_FLIP
    #elif defined (QUINOA_TAP_QWERTY)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_QWERTY_FLIP
    #elif defined (QUINOA_TAP_QWERTZ)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_QWERTZ_FLIP
    #else
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_COLEMAKDH_FLIP
    #endif
  #else
    #if defined (QUINOA_TAP_AZERTY)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_AZERTY
    #elif defined (QUINOA_TAP_BEAKL15)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_BEAKL15
    #elif defined (QUINOA_TAP_COLEMAK)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_COLEMAK
    #elif defined (QUINOA_TAP_COLEMAKDH)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_COLEMAKDH
    #elif defined (QUINOA_TAP_COLEMAKDHK)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_COLEMAKDHK
    #elif defined (QUINOA_TAP_DVORAK)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_DVORAK
    #elif defined (QUINOA_TAP_HALMAK)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_HALMAK
    #elif defined (QUINOA_TAP_WORKMAN)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_WORKMAN
    #elif defined (QUINOA_TAP_QWERTY)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_QWERTY
    #elif defined (QUINOA_TAP_QWERTZ)
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_QWERTZ
    #else
      #define QUINOA_LAYER_TAP QUINOA_ALTERNATIVES_TAP_COLEMAKDH
    #endif
  #endif
#endif
#if !defined(QUINOA_LAYERMAPPING_TAP)
  #define QUINOA_LAYERMAPPING_TAP QUINOA_MAPPING
#endif

#if !defined(QUINOA_LAYER_BUTTON)
  #define QUINOA_LAYER_BUTTON QUINOA_ALTERNATIVES_BUTTON
#endif
#if !defined(QUINOA_LAYERMAPPING_BUTTON)
  #define QUINOA_LAYERMAPPING_BUTTON QUINOA_MAPPING
#endif

#if !defined(QUINOA_LAYER_NAV)
  #if defined (QUINOA_LAYERS_FLIP)
    #if defined (QUINOA_NAV_INVERTEDT)
      #define QUINOA_LAYER_NAV QUINOA_ALTERNATIVES_NAV_INVERTEDT_FLIP
    #else
      #define QUINOA_LAYER_NAV QUINOA_ALTERNATIVES_NAV_FLIP
    #endif
  #else
    #if defined (QUINOA_NAV_INVERTEDT)
      #define QUINOA_LAYER_NAV QUINOA_ALTERNATIVES_NAV_INVERTEDT
    #elif defined (QUINOA_NAV_VI)
      #define QUINOA_LAYER_NAV QUINOA_ALTERNATIVES_NAV_VI
    #else
      #define QUINOA_LAYER_NAV QUINOA_ALTERNATIVES_NAV
    #endif
  #endif
#endif
#if !defined(QUINOA_LAYERMAPPING_NAV)
  #define QUINOA_LAYERMAPPING_NAV QUINOA_MAPPING
#endif

#if !defined(QUINOA_LAYER_MOUSE)
  #if defined (QUINOA_LAYERS_FLIP)
    #if defined (QUINOA_NAV_INVERTEDT)
      #define QUINOA_LAYER_MOUSE QUINOA_ALTERNATIVES_MOUSE_INVERTEDT_FLIP
    #else
      #define QUINOA_LAYER_MOUSE QUINOA_ALTERNATIVES_MOUSE_FLIP
    #endif
  #else
    #if defined (QUINOA_NAV_INVERTEDT)
      #define QUINOA_LAYER_MOUSE QUINOA_ALTERNATIVES_MOUSE_INVERTEDT
    #elif defined (QUINOA_NAV_VI)
      #define QUINOA_LAYER_MOUSE QUINOA_ALTERNATIVES_MOUSE_VI
    #else
      #define QUINOA_LAYER_MOUSE QUINOA_ALTERNATIVES_MOUSE
    #endif
  #endif
#endif
#if !defined(QUINOA_LAYERMAPPING_MOUSE)
  #define QUINOA_LAYERMAPPING_MOUSE QUINOA_MAPPING
#endif

#if !defined(QUINOA_LAYER_MEDIA)
  #if defined (QUINOA_LAYERS_FLIP)
    #if defined (QUINOA_NAV_INVERTEDT)
      #define QUINOA_LAYER_MEDIA QUINOA_ALTERNATIVES_MEDIA_INVERTEDT_FLIP
    #else
      #define QUINOA_LAYER_MEDIA QUINOA_ALTERNATIVES_MEDIA_FLIP
    #endif
  #else
    #if defined (QUINOA_NAV_INVERTEDT)
      #define QUINOA_LAYER_MEDIA QUINOA_ALTERNATIVES_MEDIA_INVERTEDT
    #elif defined (QUINOA_NAV_VI)
      #define QUINOA_LAYER_MEDIA QUINOA_ALTERNATIVES_MEDIA_VI
    #else
      #define QUINOA_LAYER_MEDIA QUINOA_ALTERNATIVES_MEDIA
    #endif
  #endif
#endif
#if !defined(QUINOA_LAYERMAPPING_MEDIA)
  #define QUINOA_LAYERMAPPING_MEDIA QUINOA_MAPPING
#endif

#if !defined(QUINOA_LAYER_NUM)
  #if defined (QUINOA_LAYERS_FLIP)
    #define QUINOA_LAYER_NUM QUINOA_ALTERNATIVES_NUM_FLIP
  #else
    #define QUINOA_LAYER_NUM QUINOA_ALTERNATIVES_NUM
  #endif
#endif
#if !defined(QUINOA_LAYERMAPPING_NUM)
  #define QUINOA_LAYERMAPPING_NUM QUINOA_MAPPING
#endif

#if !defined(QUINOA_LAYER_SYM)
  #if defined (QUINOA_LAYERS_FLIP)
    #define QUINOA_LAYER_SYM QUINOA_ALTERNATIVES_SYM_FLIP
  #else
    #define QUINOA_LAYER_SYM QUINOA_ALTERNATIVES_SYM
  #endif
#endif
#if !defined(QUINOA_LAYERMAPPING_SYM)
  #define QUINOA_LAYERMAPPING_SYM QUINOA_MAPPING
#endif

#if !defined(QUINOA_LAYER_FUN)
  #if defined (QUINOA_LAYERS_FLIP)
    #define QUINOA_LAYER_FUN QUINOA_ALTERNATIVES_FUN_FLIP
  #else
    #define QUINOA_LAYER_FUN QUINOA_ALTERNATIVES_FUN
  #endif
#endif
#if !defined(QUINOA_LAYERMAPPING_FUN)
  #define QUINOA_LAYERMAPPING_FUN QUINOA_MAPPING
#endif